FAULT_NONE = 0
FAULT_TMOUT = 1
FAULT_CRASH = 2
FAULT_ERROR = 3
FAULT_NOINST = 4
FAULT_NOBITS = 5

FUZZER_STOP = 6

HASH_CONST = 0xa5b35705

MAP_SZ_POW2 = 16
MAP_SZ = 2**MAP_SZ_POW2

TRIM_START_STEPS = 16
TRIM_END_STEPS 	 = 1024
TRIM_MIN_BYTES 	 = 4

INFINITE = 0xFFFFFFFF